### ISSUE TITLE
Incompatible with WebStorm 2020.1

### ISSUE THREAD

**Issue by razorness** [lexand/enclosing-jidea-plugin#7] opened 2020-04-23 15:22 UTC
IDE throws following message:

`Plugin Error: Plugin "Enclosing Plugin" is incompatible (until build 193.SNAPSHOT < WS-201.6668.106).`

Environment:
```
WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

Probably related to #6

**Comment by lexand** [comment] 2020-04-24 05:57
duplicate of #6

**Closed as completed by lexand** 2020-04-24 05:57 UTC
